### ISSUE TITLE
Difference to org-mime

### ISSUE THREAD

**Issue by dakra** [jeremy-compostella/org-msg#1]
I use [org-mime](https://github.com/org-mime/org-mime) to write my
html mails with mu4e (as I think most people do).

Can you make a feature comparison table or something
so people can see if they should use `org-msg` or `org-mime`.

**Comment by jeremy-compostella** [comment]
I agree that this is good question/idea.  I don't have enough recent experience with org-mime to draw a fair comparison though. 

I tried to use org-mime a year and half ago but was disappointed by a few things, then I tried another one which was named outlook-style but it was using muse instead of org mode so I hacked it to use org mode.  But this module was buggy, had some external dependency and was not reliable.  More importantly HTML email CSS wasn't handled properly.

The pain points to me with org-mime for me are:
1. The mail composing (I don't use mu4e) is not well integrated, org-msg works out of the box with the  gnus/message-mode combo.   org-msg has org-msg-edit mode major mode which a mix of message-mode and org-mode so you get the right colorization and features.  It is having the best of the two worlds at the same time.
2. I needed to reply in a outlook friendly style (don't get me wrong it is not something I really like but it helps me to fade in at work).  And I wanted it to work just by calling the usual gnus-summary-followup-with-original. 
3. org-mime CSS customization is a bit complicated to me.  In org-msg you can customize the org-msg-enforce-css variable to easily configure the style you want.  Also, org-msg use org-mode to generate the HTML code but handle the CSS by itself to fix email CSS requirements.  Having a style tag in the mail header is painful because you don't know where it originates from and how to update it.  That's why org-mode do its own inline CSS.  Also, I use org mode extensively and I figured over time that the style I want to use in my mail is not the same that I want to use when I generate HTML for some documentation I wrote in org-mode.  org-msg customization helps me with that.
4. File attachment was not working well.  I wanted something as simple as the org-attach feature so I implemented with a property mechanism in org-msg.  Of course image inline attachement is also supported as it is with org mime as far as I remember.
5. Reliability: back then I had bad experience with the other solutions I tried.  CSS was a mess (leading to email display issue), attachment were not working all the time, ... I needed something very stable as I wanted to use it every days at work.

**Comment by dakra** [comment]
Thanks for the thorough explanation.
org-mime got a lot better (more stable) in the last year.
But I don't write a lot of html mail so
I rarely use it.
The `org-msg-mode` sounds nice.
I'll try it out next time when I write some outlook user ;)

Closing this as it's not really an issue :)
