### ISSUE TITLE
todos are not highlighted correctly in generated html

### ISSUE THREAD

**Issue by lordpretzel** [jeremy-compostella/org-msg#14]
When previewing or sending a message that contains org-todo items, they are not highlighted. The problem seems to stem from `org-msg-html--todo` which calls `color-rgb-to-hex` which takes an optional input parameter to determine how many bytes to use per color which is set to 4 per default in the emacs 27 version I am using. The result is that colors get encoded as 12 instead 6 character hex which are not accepted by the browser. 

Possible fix:
* using the optional parameters of `color-rgb-to-hex` to ensure that only 2 bytes are used per color:

~~~lisp
(apply 'color-rgb-to-hex (append (color-name-to-rgb ,val) '(2))
~~~

instead of 

~~~lisp
(apply 'color-rgb-to-hex (color-name-to-rgb ,val))
~~~

in `org-msg-html--todo`

~~~lisp
(defun org-msg-html--todo (orig-fun todo &optional info)
  "Format todo keywords into HTML.
This function is used as an advice function of `org-html--todo'.
- ORIG-FUN is the original function.
- TODO is a TODO keyword.
- INFO is a property list."
   (cl-macrolet ((add-if-exist (val lst sym)
  	         `(when ,val
		    (push (cons ,sym (apply 'color-rgb-to-hex
					    (append (color-name-to-rgb ,val) '(2))))
			  ,lst))))
    (if org-msg-export-in-progress
	(let ((face (org-get-todo-face todo)))
	  (when (and todo face)
	    (let (props)
	      (add-if-exist (htmlize-face-foreground face) props 'color)
	      (add-if-exist (htmlize-face-background face) props
			    'background-color)
	      (format "<span%s>%s</span>"
		      (if props
			  (format " style=\"%s\"" (org-msg-props-to-style props))
			"")
		      todo))))
      (if info
	  (funcall orig-fun todo info)
	(funcall orig-fun todo)))))
~~~

the version of `color-rgb-to-hex` in my emacs version:

~~~lisp
(defun color-rgb-to-hex  (red green blue &optional digits-per-component)
  "Return hexadecimal #RGB notation for the color specified by RED GREEN BLUE.
RED, GREEN, and BLUE should be numbers between 0.0 and 1.0, inclusive.
Optional argument DIGITS-PER-COMPONENT can be either 4 (the default)
or 2; use the latter if you need a 24-bit specification of a color."
  (or digits-per-component (setq digits-per-component 4))
  (let* ((maxval (if (= digits-per-component 2) 255 65535))
         (fmt (if (= digits-per-component 2) "#%02x%02x%02x" "#%04x%04x%04x")))
    (format fmt (* red maxval) (* green maxval) (* blue maxval))))
~~~

**Comment by jeremy-compostella** [comment]
Hi **Boris**,

Emacs 26 changed the `color-rgb-to-hex` function default behavior to encode each color component with 16 bits instead of 8 bits (see commit [7b00e956](https://emba.gnu.org/emacs/emacs/commit/7b00e956b485d8ade03c870cbdd0ae086348737b) from [Eli Zaretskii](mailto:Eli%20Zaretskii%20<eliz@gnu.org>)).

As you have already mentioned, this change also adds a `digits-per-component` optional parameter to the `color-rgb-to-hex` function so that the old behavior can be restored by passing the extra parameter value `2`.

Because I would like to still be compatible with Emacs 25 for a while, it left me with two options:

1.  Add a test of the Emacs version and pass the extra parameter if necessary
2.  Write my own implementation of `color-rgb-to-hex`

Since I don't want to have an Emacs version test in the `org-msg` module and because the implementation of `color-rgb-to-hex` for the `org-msg` module particular need fit in one line, I decided to own my own version.

I pushed the fix on the experimental branch. Could you verify that it works for you ? If it does, I will push it to the `master` branch.

**Jeremy**   
*One Emacs to rule them all*

**Comment by lordpretzel** [comment]
Hi Jeremy,

thanks! I tried the experimental branch and it works correctly. 

Best,

Boris

**Comment by jeremy-compostella** [comment]
Hi **Boris**,

Thanks for the report and the analysis.  I have just pushed the fix to the `master` branch.

I am closing this ticket.

Regards,

**Jeremy**   
*One Emacs to rule them all*
