### ISSUE TITLE
org-msg-mode will not activate automatically under mu4e

### ISSUE THREAD

**Issue by panjie** [jeremy-compostella/org-msg#15]
The org-msg-mode just don't activate automatically under mu4e when I reply some outlook style email. I could activate it in mu4e:compose mode by `org-msg-edit-mode`, but with a lot of problems.

My env:
* OS: macOS 10.14.5
* Emacs: GNU Emacs 26.3
* mu/mu4e: 1.3.5C

Configurations for org-msg:
* Installed by elpa
* Using the configurations in README

**Comment by jeremy-compostella** [comment]
Is org-msg-mode activated ?

**Comment by panjie** [comment]
Hi Jeremy

`org-msg-mode` is activated and it's value is `t`.
The module will not activate automatically on either composing or replying.
When composing, I could active it by `org-msg-edit-mode`, but seems have some problems.

**Comment by jeremy-compostella** [comment]
How do you trigger a new message composition ?

**Comment by panjie** [comment]
> How do you trigger a new message composition ?

By the default key-bindings like `e` or `r` in the header view or message view.

**Comment by jeremy-compostella** [comment]
Let's clarify a few things:
1. I don't use `mu4e` I personally uses `gnus` andI don't know what `e` or `r` keys are triggering as function in your environment. FYI, many users are using `mu4e` and `org-msg`. 
2. comments like:

> When composing, I could active it by `org-msg-edit-mode`, but seems have some problems.

are just not helpful at all.  what does that mean "have some problems" ?  You have to understand that I cannot read your mind.  If you want help with your problem you need to provide information which I can use to help you.

The `org-msg` module setups some hooks (see https://github.com/jeremy-compostella/org-msg/blob/master/org-msg.el#L910 and following).  Are these hook probably setup in your case ? For instance, is the `mu4e-compose-mode-hook` variable right ? 

What is the behavior when you run `M-x compose-mail` ? Is `org-msg-edit-mode` running ?
...

**Comment by panjie** [comment]
It OK when using `compose-mail`. So, it seems that this mode is not integrated into `mu4e` properly so it could not be activated in it.

**Comment by panjie** [comment]
It seems that mu doesn't set `mail-user-agent` to `mu4e-user-agent` so `org-msg` could not call the corresponding functions. I added the following code to my init file and found it works:
```
(setq mail-user-agent (mu4e-user-agent))
```

While, there are still problems in text editing. For example, when I type `*` the text below it will all indent automatically, including the signature and cited parts, although in fact there are no blanks in it, like the following picture.

![screen](https://user-images.githubusercontent.com/935036/67839271-37845e80-fb2e-11e9-9e2f-914f61fa8ebb.png)

**Comment by jeremy-compostella** [comment]
Hi **Pan Jie**,

I downloaded `mu4e` to have a quick look at the code and I feel like it does set the `mail-user-agent`.  Could it be the order in which you load and activate the module ?

    885  ;; happily, we can re-use most things from message mode
    886  ;;;###autoload
    887  (define-mail-user-agent 'mu4e-user-agent
    888    'mu4e~compose-mail
    889    'message-send-and-exit
    890    'message-kill-buffer
    891    'message-send-hook)
    892  ;; Without this `mail-user-agent' cannot be set to `mu4e-user-agent'
    893  ;; through customize, as the custom type expects a function.  Not
    894  ;; sure whether this function is actually ever used; if it is then
    895  ;; returning the symbol is probably the correct thing to do, as other
    896  ;; such functions suggest.
    897  (defun mu4e-user-agent ()
    898    "Return the `mu4e-user-agent' symbol."
    899    'mu4e-user-agent)
    900  

Regarding the indentation "issue" you have reported this is not an issue.  This is OrgMode.   If you use my configuration you should have noticed the `indent` in `#+STARTUP: hidestars indent inlineimages`.  If you remove this it won't indent anymore.  The fact the indentation applies to the whole content including the signature is just because AFAIK there is not way to terminate a section in OrgMode.

Regards,

**Jeremy**   
*One Emacs to rule them all*

**Comment by panjie** [comment]
Thank you for your reply.

In fact, `define-mail-user-agent` only sets the plist of the symbol `mu4e-user-agent` while doesn't bind it to `mail-user-agent`. So the manually binding is necessary.

As to the indent, thank you for your hint, although it seems not working for me. I will try to find some workaround for it.

**Comment by jeremy-compostella** [comment]
Hi **Pan Jie**,

It turns out that the Mail User Agent variable has to be defined by the end-user.  I have improved the documentation of **OrgMsg** to reflect this requirement.  Do you mind reviewing the documentation on the [experimental branch](https://github.com/jeremy-compostella/org-msg/tree/experimental) and let me know if it is clear and accurate enough ?

Regards,

**Jeremy**   
*One Emacs to rule them all*

**Comment by panjie** [comment]
Hi Jeremy,

The updated document is clear enough and should work for mu4e users.
Thanks for your improvements.

B.R.

**Comment by jeremy-compostella** [comment]
Hi **Pan Jie**,

Thanks you for your review. I pushed on the master branch and now I am closing this ticket.

Thanks for reporting this "issue".

Regards,
**Jeremy**
