### ISSUE TITLE
This mode interfers with org-contacts

### ISSUE THREAD

**Issue by noorul** [jeremy-compostella/org-msg#27]
I use org-contacts for address completion. Now when enable org-msg-mode, tab is actually bound to org-msg-tab.

**Comment by jeremy-compostella** [comment]
Hi **Noorul Islam K M**,

This is because `org-contacts` creates a hook on `message-mode` to change the `completion-at-point-functions` list and your are using `org-msg-edit-mode` instead.

The following addition to your configuration should work get it to work.

```
    (add-hook org-msg-edit-mode-hook
    	    (lambda ()
    	      (add-to-list 'completion-at-point-functions
    			   'org-contacts-message-complete-function)))

```
Regards,


**Jeremy**   
*One Emacs to rule them all*

**Comment by jeremy-compostella** [comment]
I would appreciate a feedback ...

**Comment by noorul** [comment]
Thank you for the quick response. I will try this later as I switched off this mode for the time being. Closing this.
