### ISSUE TITLE
Replying to a message in a different charset is wonky

### ISSUE THREAD

**Issue by znewman01** [jeremy-compostella/org-msg#80]
Sorry for the unspecific issue title, but it's a little tricky to describe.

I use utf8 for everything. Org-mode works, org-msg mostly works.

- if I compose a message, we're all good (both preview and sending a message). if I respond to a message in utf8, we're good
- but `org-msg-build` likes to [grab the message I'm replying to](https://github.com/jeremy-compostella/org-msg/blob/master/org-msg.el#L783) and stick the new message on
- if that message was in a different encoding, then preview doesn't work because the HTML has the charset from `original`
- the email sends with *mail* `charset=utf-8` but an *HTML* charset of the original message. Some mail clients I've tested display this correctly, but it's a weird thing to send.

I've worked around this with the following hack (wrapping `org-msg-build` and fixing the content attribute:

```emacs-lisp
(defun force-utf8 (xml)
  (when (eq (car xml) 'meta)
    (let ((content (assq 'content (cadr xml))))
      (when content
        (setcdr content "text/html; charset=utf-8")))))

(advice-add 'org-msg-build :filter-return (lambda (xml) (org-msg-xml-walk xml #'force-utf8) xml))
```

This means that the quoted reply is messed up due to an encoding mismatch.

I'm not sure what the right thing to do here is.

**Comment by jeremy-compostella** [comment]
Yeah I noticed that too but never really looked at most of time it was fine for me.  I spent some time trying to understand if we should do some conversion and the conclusion is that apparently it is not needed. The Emacs internal format is derived from utf-8 which mean that the string loaded from the original email are likely already in utf-8. The only real issue is indeed that the meta tag is not updated appropriately.  There may be an extra work to do if for some reason the Emacs user is not using utf-8 as its default encoding but I am not even sure.

I pushed a patch on the experimental branch which basically does what you do. Let me know if it works for you.

**Comment by morganwillcock** [comment]
I noticed the same issue issue.
I cannot comment on what the correct fix should be, but the experimental branch change fixes it for me.

**Comment by znewman01** [comment]
Thanks for the response! I'll test out replacing my workaround with yours, bug me if I haven't updated a week from now

Your conclusion also sounds quite reasonable.

**Comment by jeremy-compostella** [comment]
I have improved the patch, it should be more robust now.

**Comment by znewman01** [comment]
Okay, had a chance to test this. It seems to tod the trick (both for previews and sending messages). Both the original message and the reply render correctly.

The more I think about it, the more I think "just make sure *everything* is utf8" is a reasonable behavior that does the right thing for 99% of what I need. I can't speak for anybody else, but this seems quite reasonable to me.

Thanks again for the quick response!

**Comment by jeremy-compostella** [comment]
fix pushed to master.
